### ISSUE TITLE
什么是MovePrevious_48000Hz.raw

### ISSUE THREAD

**Issue by Hisuifeng** [Faris0520/windows-media#1]
大佬，MovePrevious_48000Hz.raw是什么文件啊，整半天没搞懂，似乎不是一般的.raw文件，其他的也是这样。

**Comment by Faris0520** [comment]
![image](https://user-images.githubusercontent.com/65797160/206906431-f0affeb1-e52b-43e7-b880-e6e8e5e8949d.png)
 I dont know, but you can search and open it on `C:\Windows\Media`.
.raw is a picture extension 🤔 , idk
